server:
  port: 8080
spring:
  application:
    name: rent-room
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/rent-room
    username: root
    password: thaimeo2003
  liquibase:
    # Remove 'faker' if you do not want the sample data to be loaded automatically
    contexts: dev, faker
    url: jdbc:mysql://localhost:3306/rent-room
    user: root
    password: thaimeo2003
    enabled: false

logging:
  level:
    root: info
    org.hibernate.sql: info
    com.n3c3.rentroom: info

rent-room:
  jwt:
    secret-key: +J6G0rkBWSO8fyrxnyuYv8tQinxzumkNrBHG30YvcX8PdW/ZkqcG6/XfwNijxuDQD16HFCedsxB8SbsM2s4Paw==
    # 2 weeks in second
    token-expiration: 1209600



